apps/evaluation/urls.py
from django.conf.urls import url
from apps.evaluation import views

urlpatterns = [
    url(r'^performance_evaluation/all/$', views.PerformanceEvaluationList.as_view(), name='performance_evaluation_all'),
    url(r'^performance_evaluation/detail/(?P<pk>\d+)/$', views.PerformanceEvaluationDetail.as_view(), name='performance_evaluation_detail'),
    url(r'^performance_evaluation/$', views.pe_list, name="pe_list"),
    url(r'^performance_evaluation/(?P<slug>\d+)/$', views.pe_detail, name="pe_detail"),
    url(r'^performance_evaluation/(?P<slug>\d+)/popup/$', views.pe_popup, name="pe_popup"),
    url(r'^performance_evaluation/create/$', views.PerformanceEvaluationCreation.as_view(), name='performance_evaluation_create'),
    url(r'^performance_evaluation/edit/(?P<pk>\d+)$', views.PerformanceEvaluationUpdate.as_view(), name='performance_evaluation_edit'),
    url(r'^performance_evaluation/delete/(?P<pk>\d+)$', views.PerformanceEvaluationDelete.as_view(), name='performance_evaluation_delete'),
    url(r'^perform_eval/delete/(?P<pk>\d+)$', views.performance_evaluation_delete, name='perform_eval_delete'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_tc/all/$', views.CatalogTCList.as_view(), name='catalog_tc_all'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_tc/detail/(?P<pk>\d+)/$', views.CatalogTCDetail.as_view(), name='catalog_tc_detail'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_tc/create/$', views.CatalogTCCreation.as_view(), name='catalog_tc_create'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_tc/edit/(?P<pk>\d+)$', views.CatalogTCUpdate.as_view(), name='catalog_tc_edit'),
    #url(r'^(?P<perform_eval_pk>\d+)/catalog_tc/delete/(?P<pk>\d+)$', views.CatalogTCDelete.as_view(), name='catalog_tc_delete'),
    url(r'^catalog_tc/delete/$', views.catalog_tc_delete, name='catalog_tc_delete'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_uc/all/$', views.CatalogUCList.as_view(), name='catalog_uc_all'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_uc/detail/(?P<pk>\d+)/$', views.CatalogUCDetail.as_view(), name='catalog_uc_detail'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_uc/create/$', views.CatalogUCCreation.as_view(), name='catalog_uc_create'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_uc/edit/(?P<pk>\d+)$', views.CatalogUCUpdate.as_view(), name='catalog_uc_edit'),
    #url(r'^(?P<perform_eval_pk>\d+)/catalog_uc/delete/(?P<pk>\d+)$', views.CatalogUCDelete.as_view(), name='catalog_uc_delete'),
    url(r'^catalog_uc/delete/(?P<pk>\d+)$', views.catalog_uc_delete, name='catalog_uc_delete'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_tw/all/$', views.CatalogTWList.as_view(), name='catalog_tw_all'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_tw/detail/(?P<pk>\d+)/$', views.CatalogTWDetail.as_view(), name='catalog_tw_detail'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_tw/create/$', views.CatalogTWCreation.as_view(), name='catalog_tw_create'),
    url(r'^(?P<perform_eval_pk>\d+)/catalog_tw/edit/(?P<pk>\d+)$', views.CatalogTWUpdate.as_view(), name='catalog_tw_edit'),
    #url(r'^(?P<perform_eval_pk>\d+)/catalog_utw/delete/(?P<pk>\d+)$', views.CatalogTWDelete.as_view(), name='catalog_tw_delete'),
    url(r'^catalog_tw/delete/(?P<pk>\d+)/$', views.catalog_tw_delete, name='catalog_tw_delete'),
    url(r'^(?P<perform_eval_pk>\d+)/inst_unit_eval/all/$', views.inst_unit_eval_all, name='inst_unit_eval_all'),
    url(r'^(?P<perform_eval_pk>\d+)/inst_unit_eval/detail/(?P<pk>\d+)/$', views.inst_unit_eval_detail, name='inst_unit_eval_detail'),
    url(r'^(?P<perform_eval_pk>\d+)/inst_unit_eval/create/$', views.inst_unit_eval_create, name='inst_unit_eval_create'),
    url(r'^(?P<perform_eval_pk>\d+)/inst_unit_eval/edit/(?P<pk>\d+)$', views.inst_unit_eval_edit, name='inst_unit_eval_edit'),
    url(r'^inst_unit_eval/delete/(?P<pk>\d+)/$', views.inst_unit_eval_delete, name='inst_unit_eval_delete'),
    url(r'^performance_eval_to_evaluate/all/$', views.performance_eval_to_evaluate, name='performance_eval_to_evaluate'),
    # url(r'^personal_eval_to_evaluate/all/$', 'evaluation.views.personal_eval_to_evaluate', name='personal_eval_to_evaluate'),
    url(r'^personal_eval_to_evaluate/all/$', views.personal_eval_to_evaluate_all, name='personal_eval_to_evaluate_all'),
    url(r'^personal_eval_update/(?P<pk>\d+)$', views.personal_eval_update, name='personal_eval_update'),
    # url(r'^personal_evaluation/all/$', 'evaluation.views.personal_evaluation_all', name='personal_evaluation_all'),
    url(r'^personal_evaluation/all/$', views.PersonalEvaluationList.as_view(), name='personal_evaluation_all'),
    url(r'^personal_evaluation_low_performance/all/$', views.PersonalEvaluationLowList.as_view(), 
        name='personal_evaluation_low_all'),
    url(r'^personal_evaluation/evaluate/(?P<pk>\d+)/$', views.personal_evaluation_evaluate, name='personal_evaluation_evaluate'),
    url(r'^finalize_person_eval/(?P<pk>\d+)/$', views.finalize_personal_evaluation, name='finalize_person_eval'),
    url(r'^personal_evaluation/view/(?P<pk>\d+)/$', views.personal_evaluation_view, name='personal_evaluation_view'),
    url(r'^personal_evaluation/create_for_recorey/(?P<person_eval_pk>\d+)/$',
        views.create_personal_evaluation_for_recovery,
        name='create_personal_evaluation_for_recovery'),
    url(r'^personal_evaluation/(?P<personal_eval_pk>\d+)/generate/$',
        views.personal_evaluation_generate,
        name='personal_evaluation_generate'),
    url(r'^activity/create/(?P<ae_pk>\d+)/$', views.activity_create, name='activity_create'),
    url(r'^knowledge/create/(?P<ke_pk>\d+)/$', views.knowledge_create, name='knowledge_create'),
    url(r'^activity/delete/$', views.activity_delete, name='activity_delete'),
    url(r'^knowledge/delete/$', views.knowledge_delete, name='knowledge_delete'),
    url(r'^technical_competence/delete/$', views.technical_competence_delete, name='technical_competence_delete'),
    url(r'^universal_competence/delete/$', views.universal_competence_delete, name='universal_competence_delete'),
    url(r'^teamwork/delete/$', views.teamwork_delete, name='teamwork_delete'),
    url(r'^chief_observation/delete/$', views.chief_observation_delete, name='chief_observation_delete'),
    url(r'^complaint/delete/$', views.complaint_delete, name='complaint_delete'),
    url(r'^technical_competence/create/(?P<tce_pk>\d+)/$', views.technical_competence_create, name='technical_competence_create'),
    url(r'^universal_competence/create/(?P<uce_pk>\d+)/$', views.universal_competence_create, name='universal_competence_create'),
    url(r'^teamwork/create/(?P<twe_pk>\d+)/$', views.teamkork_create, name='teamkork_create'),
    url(r'^chief_observation/create/(?P<pe_pk>\d+)/$', views.chief_observation_create, name='chief_observation_create'),
    url(r'^complaint/create/(?P<ce_pk>\d+)/$', views.complaint_create, name='complaint_create'),
    url(r'^catalog_tech_comp/$', views.catalog_tech_comp, name='catalog_tech_comp'),
    url(r'^catalog_univ_comp/$', views.catalog_univ_comp, name='catalog_univ_comp'),
    url(r'^catalog_teamwork/$', views.catalog_teamwork, name='catalog_teamwork'),
    url(r'^report/$', views.some_view, name='report'),
    url(r'^(?P<perform_eval_pk>\d+)/selection_contracts/$', views.selection_contracts, name='selection_contracts'),
    url(r'^performance_evaluation/(?P<perform_eval_pk>\d+)/initiate/$', views.initiate_performance_eval, name='initiate_performance_eval'),
    url(r'^performance_evaluation/(?P<perform_eval_pk>\d+)/finalize/$', views.finalize_performance_eval, name='finalize_performance_eval'),
    url(r'^(?P<inst_unit_eval_pk>\d+)/initiate_inst_unit_eval/$', views.initiate_inst_unit_eval, name='initiate_inst_unit_eval'),
    url(r'^(?P<inst_unit_eval_pk>\d+)/finalize_inst_unit_eval/$', views.finalize_inst_unit_eval, name='finalize_inst_unit_eval'),
    url(r'^personal_evaluation_report/(?P<person_eval_pk>\d+)/$', views.personal_evaluation_report, name='personal_evaluation_report'),
    url(r'^hola_pdf/$', views.hola_pdf, name='hola_pdf'),
    url(r'^uploads/simple/$', views.simple_upload, name='simple_upload'),
    url(r'^uploads/form/(?P<pe_pk>\d+)/$', views.model_form_upload, name='model_form_upload'),
    url(r'^uploads/form/(?P<pe_pk>\d+)/(?P<doc_pk>\d+)/$', views.model_form_upload_edit, name='model_form_upload_edit'),
    url(r'^insert_data/$', views.insert_items_catalog_AREAESTUDIO, name='insert_data'),
    ]

humanresource/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.urlresolvers import reverse_lazy
# from apps.institution import views
# from apps.schedule import views
# from apps.person import views
# from apps.contract import views
# from apps.accounts import views
from django.contrib.auth import login, logout
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.security.urls')),
    url(r'^evaluation/', include('apps.evaluation.urls', namespace='evaluation')),
    url(r'^accounting_finance/', include('apps.accounting_finance.urls', namespace='accounting_finance')),
    url(r'^catalogo/', include('apps.settings.urls', namespace='catalogo')),
    url(r'^institution/', include('apps.institution.urls', namespace='institution')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^roles/', include('apps.roles.urls', namespace='roles')),
    url(r'^partidas/', include('apps.partidas.urls', namespace='partidas')),
    url(r'^schedule/', include('apps.schedule.urls', namespace='schedule')),
    url(r'^person/', include('apps.person.urls', namespace='person')),
    url(r'^contract/', include('apps.contract.urls', namespace='contract')),
    url(r'^employee/', include('apps.employee.urls', namespace='employee')),
    url(r'^vacacion/', include('apps.vacacion.urls', namespace='vacacion')),
    url(r'^cambios/', include('apps.cambios.urls', namespace='cambios')),
    url(r'^curriculum/', include('apps.curriculum.urls', namespace='curriculum')),
    url(r'^personnelactions/', include('apps.personnel_actions.urls', namespace='personnelactions')),
    url(r'^economicdata/', include('apps.economicdata.urls', namespace='economicdata')),
    url(r'^permissions/', include('apps.permissions.urls', namespace='permissions')),
    url(r'^login/$', login, {'template_name': 'app/login.html'}, name='security_login'),
    url(r'^logout/$', logout, {'next_page': reverse_lazy('security_main')}, name='security_logout'),

]
# urlpatterns += staticfiles_urlpatterns()

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Municipio de Loja'

apps/evaluation/templates/personal_evaluation/activity_aux.html
<form class="well activity_form" method="post" action="/activity/create/9" id="activity_form">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Editing Contact</h3>
  </div>
  <div class="modal-body">
       {% csrf_token %}
       {{form.as_p}}
  </div>
  <div class="modal-footer">
       <input class="btn btn-primary" type="submit" value="Save" />
       <input name="cancel" class="btn" type="submit" value="Cancel"/>
  </div>
</form>

apps/evaluation/templates/personal_evaluation/chief_observation.html
{% load l10n %}
{% load crispy_forms_tags %}
<form class="chief-observation-form" method='POST' action="{% url "evaluation:chief_observation_create" personal_eval.pk %}" id='chief-observation-form'>
{% csrf_token %}
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">Observaciones</h4>
    </div>
    <div class="modal-body">
       {{form|crispy}}
    </div>
    <div class="modal-footer">      
      <button type="button" class="btn btn-default" data-dismiss="modal">
        <span class="glyphicon glyphicon-share"></span> Salir
      </button>
       <button type="submit" class="btn btn-success" name="save" id='submit_chief_observation_form'>
        <span class="glyphicon glyphicon-check"></span> Guardar
      </button>
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
</form>
<script type="text/javascript">

  $('#chief-observation-form').on('submit', function() {
        console.log('intro submit');
        $.ajax({ 
            type: $(this).attr('method'), 
            url: this.action, 
            data: $(this).serialize(),
            context: this,
            success: function(data, status) {
                $('#chief_observation_modal').modal('hide');
                console.log(data.status);
                console.log('>>>');
                console.log(data);
                BootstrapDialog.show({
                  type: BootstrapDialog.TYPE_SUCCESS, 
                    title: 'Guardado exitoso.',
                    message: 'La observación acerca del servidor público ha sido guardado exitosamente.',
                    closable: false,
                    buttons: [ {
                        label: 'Aceptar',
                        action: function(dialog){
                            dialog.close();
                            // window.location="/evaluation/personal_evaluation/evaluate/" + personal_eval_id + "/";
                            window.location = " {% url "evaluation:personal_evaluation_evaluate" personal_eval.pk %} ";
                        }
                    }]
                });
            },
            //error: function(XMLHttpRequest, textStatus, errorThrown) {
            error: function(data, status) {
              //$('#knowledgeModal').html(data);
              $('#chief_observation_modal').html(data.responseText);
              console.log(data.status);
              console.log('>>>');
              console.log(data.responseText);
            }
        });
        return false;
    });

</script>

apps/evaluation/templates/personal_evaluation/document_form.html
{% extends "base.html" %}
{% load evaluation_extras  %}
{% load l10n %}
{% load crispy_forms_tags %}


{% block title%}
{% endblock  %}

{% block heading %}
  	<div style="margin: 20px;">
		<p class="titulo-form">DOCUMENTO ADJUNTO:</p>
	</div>  
	<hr/><br/>
{% endblock %}


{% block content %}
	
	{% include "messages.html" %}

	<form class="form-horizontal" method="post" enctype="multipart/form-data">
	   	{% csrf_token %}

		{% for field in form.visible_fields %}
		    <div class="form-group">
		      {{ field.errors }}
		      <label class="col-sm-2 control-label" for="{{ field.name }}">{{ field.label }}</label>
		        <div class="col-sm-8">
		      {{ field|addclass:'form-control' }}
		      </div>
		    </div>
		{% endfor %}

		 <hr/><br/>

	    <div class="form-group">
	    	<button type="submit" class="btn btn-success" name="save">
		    	<span class="glyphicon glyphicon-ok"></span> Guardar
		    </button>
		 	<a href="{% url "evaluation:personal_evaluation_all" %}" class="btn btn-primary" >
		 		<span class="glyphicon glyphicon-share-alt"></span> Salir
		 	</a>
		</div>

	</form>
{% endblock %}

{% block javascript %}
	 <script>
    	
    </script>
{% endblock %}

apps/evaluation/templates/personal_evaluation/evaluation_list.html
{% extends "base.html" %}
{% load evaluation_extras  %}

{% load staticfiles %}

{% block title %}
  Evaluación de desempeño
{% endblock %}

{% block heading %}
  
<h5> EVALUACIONES PERSONALES </h5>
<hr style="width: 100%; color: black; height: 1px; background-color:black;" />
{% endblock %}

{% block content %}
<form method="GET" class="form-horizontal" role="form">
  <div class="form-group">
    <label class="required col-lg-1 control-label" for="id_evaluation_date">Fecha evaluación:</label>
    <div class="col-lg-5">
    <input class="form-control" id="id_evaluation_date" name="evaluation_date" size="10" type="text" placeholder="Fecha de evaluación" value="{{ evaluation_date }}">
    </div>
  </div>
  <div class="form-group">
  <div class="col-lg-offset-1 col-lg-10">
      <input type="submit" class="btn btn-default" value="Buscar" />
    </div>
  </div>
</form>

<!-- Output table -->
  
  <div id="progress" style="display: none;" >Please wait while the page is loading.</div>

  <div class="row">

    <table class="table table-striped table-hover" cellpadding=0 cellspacing=10>
      <thead>
        <tr>
          <th>Evaluado</th>
          <th>Período desde</th>
          <th>Período hasta</th>
          <th>Estado</th> 
          <th>Acciones</th>
        </tr>
      </thead>  
      <tbody>
      {% for evaluation in personal_evaluation_list %}
        <tr>
          <td>{{ evaluation.evaluated.person }}</td>          
          <td>{{ evaluation.period_from }}</td>
          <td>{{ evaluation.period_to }}</td>
          <td>{{ evaluation|setstate:evaluation.state }}</td>
          <td> 
          {% if evaluation.state == "GENERATED" %}
              <a href="{% url "evaluation:personal_evaluation_generate"%}">Generar</a>
              <button type="button" id="btn_generate">Generate</button>
          {% elif evaluation.state == "INITIATED" %}
              <a href="{% url "evaluation:personal_evaluation_evaluate" evaluation.pk %}">Registrar</a> |
          {% endif %}
          </td>
          <!--<td>  <a href="{% url "evaluation:performance_evaluation_detail" evaluation.id %}">Ver</a> | 
                <a href="{% url "evaluation:performance_evaluation_edit" evaluation.id %}">Editar</a> | 
                <a href="{% url "evaluation:performance_evaluation_delete" evaluation.id %}">Borrar</a>  </td>
        </tr>-->
      {% endfor %}
      </tbody>
    </table>
  </div>

<!-- Pagination controls -->
{% if is_paginated %}
  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li>
          <a href="?state={{ state }}&year={{ year }}&page={{ page_obj.previous_page_number }}">
            <span>Previous</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#">
            <span>Previous</span>
          </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
          <a href="?state={{ state }}&year={{ year }}&page={{ page }}">{{ page }}</a>
        </li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li>
          <a href="?state={{ state }}&year={{ year }}&page={{ page_obj.next_page_number }}">
            <span>Next</span>
          </a>
        </li>
      {% else %}
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

{% endblock %}

{% block javascript %}
  <script>
    $('#btn_generate').on('click', function(){   
      /*$.ajax('/evaluation/personal_evaluation/generate/', {                          
        success: function(response){   
          console.log("respuesta:");
          console.log(response);
          location.reload();
        },
        type: 'GET',      
      });*/
      $.ajax({
        url:url,
        data:data,
        success:succes,
        dataType:dateType
      });
    });

  </script>

{% endblock %}

apps/evaluation/templates/personal_evaluation/jm.html
<h1>New post</h1>
<form method='POST' action='{% url "evaluation:job_management_create" 9 %}' id='contactForm'>
  {% csrf_token %} 
  {{ form.as_p }}
  <input name="save" class="btn btn-primary" type="submit" value="Save" />
  <input name="cancel" class="btn" type="submit" value="Cancel"/>
</form>

apps/evaluation/templates/personal_evaluation/personal_eval_low_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Evaluaciones de desempeño
{% endblock %}

{% block heading %}

 {% for message in messages %}
    <div class = "alert alert-{{ message.tags }} alert-dismissable">
       <button type = "button" class = "close" data-dismiss = "alert" aria-hidden = "true">
          &times;
       </button>

        {% if message.tags == "success" %}
          <strong>Correcto!</strong> {{ message }}
        {% endif %}

        {% if message.tags == "danger" %}
          <strong>Error!</strong> {{ message }}
        {% endif %}

    </div>

  {% endfor %}

<h5> EVALUACIONES CON BAJO DESEMPEÑO</h5>
<hr style="width: 100%; color: black; height: 1px; background-color:black;" />
{% endblock %}

{% block content %}
<form method="GET" class="form-horizontal" role="form">
  <div class="form-group">
    <label class="required col-lg-1 control-label" for="id_inst_unit">Unidades institucionales:</label>
    <div class="col-lg-5">
      <select id="id_inst_unit" name="inst_unit" class="form-control">
        {% for key, value in list_inst_unit %}
           <option value="{{ key }}"
          {% if key == inst_unit %}selected="selected"{% endif %}>
          {{ value }}
          </option>
        {% endfor %}
      </select>
    </div>
    <label class="required col-lg-1 control-label" for="id_year">Año:</label>
    <div class="col-lg-5">
    <input id="id_year" name="year" maxlength="4" type="text" class="form-control"
      placeholder="Año de evaluación" value="{{ year }}">
    </div>
  </div>
  <div class="form-group">
    <label class="required col-lg-1 control-label" for="id_evaluation">Identificación:</label>
    <div class="col-lg-5">
      <input id="id_identification" name="identification" maxlength="4" type="text" class="form-control"
      	placeholder="Identificación" value="{{ identification }}">
    </div>
    <label class="required col-lg-1 control-label" for="id_evaluation">Nombres:</label>
    <div class="col-lg-5">
      <input id="id_names" name="names" maxlength="15" type="text" class="form-control"
      	placeholder="Nombres o apellidos" value="{{ names }}">
    </div>
  </div>

  <div class="form-group">
    <label class="required col-lg-1 control-label" for="id_score">Valoración:</label>
    <div class="col-lg-5">
      <select id="id_score" name="score" class="form-control">
        {% for key, value in list_score.items %}
           <option value="{{ key }}"
          {% if key == score %}selected="selected"{% endif %}>
          {{ value }}
          </option>
        {% endfor %}
      </select>
    </div>
  </div>

  <div class="form-group">
  <div class="col-lg-offset-1 col-lg-10">
       <button type="submit" class="btn btn-info">
          <span class="glyphicon glyphicon-search"></span> Buscar
      </button>
    </div>
  </div>
</form>

<!-- Output table -->

  <div class="row">

    <table class="table table-striped table-hover" cellpadding=0 cellspacing=10>
      <thead>
        <tr>
          <th class="col-md-2">Unidad institucional</th>
          <th class="col-md-1">Evaluación</th>
          <th class="col-md-1">Calificación</th>
          <th class="col-md-2">Identificación</th>
          <th class="col-md-3">Nombres</th>
          <th class="col-md-2">Acciones</th>
        </tr>
      </thead>
      <tbody>
      {% for person_eval in  object_list %}
        <tr>
          <td class="col-md-2">{{ person_eval.institutional_unit_evaluation.institutional_unit.institutional_unit }}</td>
          <td class="col-md-1">{{ person_eval.institutional_unit_evaluation.performance_evaluation.year }}</td>
          <td class="col-md-1">{{ person_eval.final_evaluation_percentage }}</td>
          <td class="col-md-2">{{ person_eval.evaluated.person.cedula }}</td>
          <td class="col-md-3">{{ person_eval.evaluated.person.name }} {{ person_eval.evaluated.person.lastname }} </td>
          <td class="col-md-2">
            {% if person_eval.state == 'FINALIZED' %}
              <a class="create-btn text-warning" id="create-{{ person_eval.pk}}"
                href="{% url "evaluation:create_personal_evaluation_for_recovery" person_eval.pk %}">Generar evaluación de recuperación</a>
            {% endif %}

          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>


<!-- Pagination controls -->
{% if is_paginated %}
  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li>
          <a href="?inst_unit={{ inst_unit }}&identification={{ identification }}&names={{ names }}&page={{ page_obj.previous_page_number }}">
            <span>Previous</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#">
            <span>Previous</span>
          </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
          <a href="?inst_unit={{ inst_unit }}&year={{ year }}&identification={{ identification }}&names={{ names }}&page={{ page }}">{{ page }}</a>
        </li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li>
          <a href="?inst_unit={{ inst_unit }}&year={{ year }}&identification={{ identification }}&names={{ names }}&page={{ page_obj.next_page_number }}">
            <span>Next</span>
          </a>
        </li>
      {% else %}
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

 <!-- Modal -->
  <div class="modal fade" id="create-confirm-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header modal-header-primary">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Información</h4>
        </div>
        <div class="modal-body">
          <p>Está seguro que desea crear una nueva evaluación de desempeño?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <a href="#" id="create-confirm-btn" class="btn btn-danger"><i class="icon-trash"></i>Aceptar</a>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock %}

{% block javascript %}
  <script>

      $(".create-btn").click(function() {
        console.log('intro >>>')
        $("#create-confirm-btn").attr("href", $(this).attr("href"));
        $("#create-confirm-modal").modal('toggle');
        return false;
      });

  </script>
{% endblock %}