apps/accounting_finance/urls.py
from django.conf.urls import url

from apps.accounting_finance import views

urlpatterns = [
    url(r'^accounting_period/all/$', views.AccountingPeriodList.as_view(), name='accounting_period_all'),
    url(r'^accounting_period/redirect/$', views.accounting_period_redirect, name='accounting_period_redirect'),
    url(r'^accounting_period/detail/(?P<pk>\d+)/$', views.AccountingPeriodDetail.as_view(), name='accounting_period_detail'),
    url(r'^accounting_period/create/$', views.AccountingPeriodCreation.as_view(), name='accounting_period_create'),
    url(r'^accounting_period/edit/(?P<pk>\d+)$', views.AccountingPeriodUpdate.as_view(), name='accounting_period_edit'),
    #url(r'^accounting_period/delete/(?P<pk>\d+)$', views.AccountingPeriodDelete.as_view(), name='accounting_period_delete'),
    url(r'^accounting_period/delete/$', views.accounting_period_delete, name='accounting_period_delete'),
    url(r'^accounts_plan/all/$', views.AccountsPlanList.as_view(), name='accounts_plan_all'),
    url(r'^accounts_plan/detail/$', views.AccountsPlanDetail.as_view(), name='accounts_plan_detail'),
    url(r'^accounts_plan/create/$', views.AccountsPlanCreation.as_view(), name='accounts_plan_create'),
    url(r'^accounts_plan/edit/$', views.AccountsPlanUpdate.as_view(), name='accounts_plan_edit'),
    #url(r'^accounts_plan/delete/$', views.AccountsPlanDelete.as_view(), name='accounts_plan_delete'),
    url(r'^accounts_plan/delete/(?P<pk>\d+)/$', views.accounts_plan_delete, name='accounts_plan_delete'),
    url(r'^accounting_account/all/$', views.AccountingAccountList.as_view(), name='accounting_account_all'),
    url(r'^accounting_account/create/$', views.AccountingAccountCreation.as_view(), name='accounting_account_create'),
    url(r'^accounting_account/edit/$', views.AccountingAccountUpdate.as_view(), name='accounting_account_edit'),
    url(r'^accounting_account_tree/$', views.accounting_account_tree, name='accounting_account_tree'),
    url(r'^aa_list_json/$', views.aa_list_json, name='aa_list_json'),
    url(r'^aa_object_json/$', views.aa_object_json, name='aa_object_json'),
    ]

humanresource/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.urlresolvers import reverse_lazy
# from apps.institution import views
# from apps.schedule import views
# from apps.person import views
# from apps.contract import views
# from apps.accounts import views
from django.contrib.auth import login, logout
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.security.urls')),
    url(r'^evaluation/', include('apps.evaluation.urls', namespace='evaluation')),
    url(r'^accounting_finance/', include('apps.accounting_finance.urls', namespace='accounting_finance')),
    url(r'^catalogo/', include('apps.settings.urls', namespace='catalogo')),
    url(r'^institution/', include('apps.institution.urls', namespace='institution')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^roles/', include('apps.roles.urls', namespace='roles')),
    url(r'^partidas/', include('apps.partidas.urls', namespace='partidas')),
    url(r'^schedule/', include('apps.schedule.urls', namespace='schedule')),
    url(r'^person/', include('apps.person.urls', namespace='person')),
    url(r'^contract/', include('apps.contract.urls', namespace='contract')),
    url(r'^employee/', include('apps.employee.urls', namespace='employee')),
    url(r'^vacacion/', include('apps.vacacion.urls', namespace='vacacion')),
    url(r'^cambios/', include('apps.cambios.urls', namespace='cambios')),
    url(r'^curriculum/', include('apps.curriculum.urls', namespace='curriculum')),
    url(r'^personnelactions/', include('apps.personnel_actions.urls', namespace='personnelactions')),
    url(r'^economicdata/', include('apps.economicdata.urls', namespace='economicdata')),
    url(r'^permissions/', include('apps.permissions.urls', namespace='permissions')),
    url(r'^login/$', login, {'template_name': 'app/login.html'}, name='security_login'),
    url(r'^logout/$', logout, {'next_page': reverse_lazy('security_main')}, name='security_logout'),

]
# urlpatterns += staticfiles_urlpatterns()

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Municipio de Loja'

apps/accounting_finance/models.py
from django.db import models
from apps.institution.models import Institucion
from datetime import date, datetime

# Create your models here.

STATES_ACTIVE_INACTIVE_CHOICES = (
    ('ACTIVE', 'Activo'),
    ('INACTIVE', 'Inactivo'),
)

STATES_YES_NOT_CHOICES = (
    ('YES', 'Sí'),
    ('NOT', 'No'),
)


class AccountingPeriod(models.Model):  # Periodo contable
    code = models.CharField(verbose_name='Código', max_length=100, unique=True)  # Codigo del periodo contable
    year = models.CharField(verbose_name='Año (Nombre)', max_length=4)  # Anio o nombre del periodo contable
    start_date = models.DateField(verbose_name='Fecha de inicio',
                                  default=date.today)  # Fecha de inicio del periodo contable
    end_date = models.DateField(verbose_name='Fecha de fin', default=date.today)  # Fecha de fin del perido contable
    state = models.CharField(verbose_name='Estado', max_length=10,
                             choices=STATES_ACTIVE_INACTIVE_CHOICES,
                             default='ACTIVE')  # Estado de la período contable
    observation = models.TextField(verbose_name='Observación')  # Observacion referente al periodo contable
    institution = models.ForeignKey(Institucion, on_delete=models.CASCADE,
                                    verbose_name='Institución')  # Referencia a la institución a la que pertenece

    class Meta:
        verbose_name = "Período contable"
        verbose_name_plural = "Períodos contables"

    def __str__(self):
        return self.code


class AccountsPlan(models.Model):  # Plan de cuentas
    code = models.CharField(verbose_name='Código', max_length=100, unique=True)  # Codigo del plan de cuentas
    name = models.CharField(verbose_name='Nombre', max_length=250)  # Nambre del plan de cuentas
    state = models.CharField(verbose_name='Estado', max_length=10,
                             choices=STATES_ACTIVE_INACTIVE_CHOICES,
                             default='ACTIVE')  # Estado del plan de cuentas
    observation = models.TextField(verbose_name='Observación')  # Observacion referente la plan de cuentas
    accounting_period = models.ForeignKey(AccountingPeriod, on_delete=models.CASCADE,
                                          verbose_name='Período contable')  # Referencia al periodo contable al que pertence el plan de cuentyas

    class Meta:
        verbose_name = "Plan de cuentas"
        verbose_name_plural = "Plan de cuentas"

    def __str__(self):
        return self.code


class AccountingAccount(models.Model):  # Cuenta contable
    code = models.CharField(verbose_name='Código', max_length=100, unique=True)  # Codigo de la cuenta contable
    name = models.CharField(verbose_name='Nombre', max_length=250)  # Nombre de la cuenta contable
    type = models.CharField(verbose_name='Tipo', max_length=50)  # Tipo de la cuenta contable
    level = models.IntegerField(verbose_name='Nivel', default=1)  # Nivel de la cuenta, indica el numero de padres
    state = models.CharField(verbose_name='Estado', max_length=10,
                             choices=STATES_ACTIVE_INACTIVE_CHOICES,
                             default='ACTIVE')  # Estado de la cuenta contable
    include_jornalization = models.CharField(verbose_name='Incluir en jornalización', max_length=3,
                                             choices=STATES_YES_NOT_CHOICES,
                                             default='NOT')  # Si esta incluida en la jornalizacion
    print = models.CharField(verbose_name='Imprimir', max_length=3,
                             choices=STATES_YES_NOT_CHOICES, default='NOT')  # Opcion si se imprime en la jornalizacion
    order_print = models.IntegerField(
        verbose_name='Orden de impresión')  # Orden de impresion dentro de la jornalizacion
    movement = models.CharField(verbose_name='Cuenta de movimiento', max_length=3,
                                choices=STATES_YES_NOT_CHOICES,
                                default='NOT')  # Induca si la cuenta es de movimiento o no
    name_parent = None
    accounts_plan = models.ForeignKey(AccountsPlan, on_delete=models.CASCADE,
                                      verbose_name='Plan de cuentas')  # Plan de cuentas al que pertenece
    parent = models.ForeignKey('self', models.SET_NULL, blank=True, null=True,
                               verbose_name='Cuenta contable padre')  # Cuenta contable padre

    class Meta:
        verbose_name = "Cuenta contable"
        verbose_name_plural = "Cuentas contables"
        unique_together = (('code', 'name'),)

    def __str__(self):
        return '%s - %s' % (self.code, self.name)

    def natural_key(self):
        # return (self.code, self.name)
        return ('%s - %s' % (self.code, self.name))


class BudgetClassifier(models.Model):  # Clasificador presupuestario
    code = models.CharField(verbose_name='Código', max_length=100, unique=True)  # Codigo del clasificador presuúestario
    name = models.CharField(verbose_name='Nombre', max_length=250)  # Nambre del clasificador presupuestario
    state = models.CharField(verbose_name='Estado', max_length=10,
                             choices=STATES_ACTIVE_INACTIVE_CHOICES,
                             default='ACTIVE')  # Estado del clasificador presupuestario
    observation = models.TextField(verbose_name='Observación')  # Observacion referente al clasificador presupuestario
    accounting_period = models.ForeignKey(AccountingPeriod, on_delete=models.CASCADE,
                                          verbose_name='Período contable')  # Referencia al periodo contable al que pertence el plan de cuentas

    class Meta:
        verbose_name = "Clasificador presupuestario"
        verbose_name_plural = "Clasificador presupuestario"

    def __str__(self):
        pass


class BudgetItem(models.Model):  # Partida presupuestaria
    code = models.CharField(verbose_name='Código', max_length=100, unique=True)  # Codigo de la partida presupuestaria
    name = models.CharField(verbose_name='Nombre', max_length=250)  # Nombre de la partida presupuestaria
    type = models.CharField(verbose_name='Tipo', max_length=50)  # Tipo de partida presupuestaria
    state = models.CharField(verbose_name='Estado', max_length=10,
                             choices=STATES_ACTIVE_INACTIVE_CHOICES,
                             default='ACTIVE')  # Estado de la partida presupuestaria
    print = models.CharField(verbose_name='Imprimir', max_length=3,
                             choices=STATES_YES_NOT_CHOICES, default='YES')  # Opcion si se imprime
    order_print = models.IntegerField(
        verbose_name='Orden de impresión')  # Orden de impresion de la partida presuúestaria
    budget_classifier = models.ForeignKey(BudgetClassifier, on_delete=models.CASCADE,
                                          verbose_name='Clasificador preupuestario')  # Referencia al clasificador presupuestario al que pertenece

    class Meta:
        verbose_name = "Partida presupuestaria",
        verbose_name_plural = "Partidas presupestarias"

    def __str__(self):
        pass

apps/accounting_finance/forms.py
from django import forms
from django.forms import ModelForm
from .models import (AccountingPeriod, AccountsPlan, AccountingAccount)

class AccountinPeriodForm(ModelForm):
    start_date = forms.DateField(label='Birth Date', required=True,  
        widget=forms.DateTimeInput(format='%d/%m/%Y', attrs={
            'placeholder':'Select a date'
        })
    )
    # end_date = forms.DateField(widget=forms.DateInput(format = '%d/%m/%Y', attrs={
    #         'placeholder':'Select a date'
    #     }), input_formats=('%d/%m/%Y'),
    #     required=False)

    class Meta:
       model = AccountingPeriod
       fields = '__all__'
       exclude=[]

    def __init__(self, *args, **kwargs):
        super(AccountingPeriod, self).__init__(*args, **kwargs)
        #self.fields['end_date'].widget = forms.DateInput(format=('%d/%m/%Y'), attrs={'placeholder':'Select a date'})

class AccountsPlanForm(ModelForm):
    class Meta:
       model = AccountsPlan
       fields = '__all__'
       exclude=['accounting_period']

class AccountingAccountForm(ModelForm):
    #parent = forms.CharField(label='Cuenta padre')
    field_order = ['parent', 'code', 'name', 'type', 'level', 'state', 'include_jornalizacion', 'print', 'order_print', 'movement']
    class Meta:
        model = AccountingAccount
        fields = '__all__'
        exclude=['accounts_plan']
        

apps/accounting_finance/templates/accounting_account_delete.html
accounting_accounts_delete.html

apps/accounting_finance/templates/accounting_account_detail.html
accounting_account_detail.html

apps/accounting_finance/templates/accounting_account_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Cuentas contables:
{% endblock %}

{% block heading %}
<h5> Cuentas contables </h5>
<p>
  <a href="{% url "accounting_finance:accounting_account_create" %}?accounts_plan={{ accounts_plan.pk }}" class="btn btn-info">Nuevo</a>
  <a href="{% url "accounting_finance:accounts_plan_all" %}?accounting_period={{ accounts_plan.accounting_period.pk }}" class="btn btn-info pull-right">Regresar</a>
</p>
<hr style="width: 100%; color: black; height: 1px; background-color:black;" />
{% endblock %}

{% block content %}
<!-- Output table -->
  <div class="row">
    <table class="table table-striped table-hover" cellpadding=0 cellspacing=10>
      <thead>
        <tr>
          <th>Código</th>
          <th>Nombre</th>
          <th>Tipo</th>
          <th>Estado</th>
          <th>Acciones</th>
        </tr>
      </thead>  
      <tbody>
      {% for obj in object_list %}
        <tr>
          <td>{{ obj.code }}</td>          
          <td>{{ obj.name }}</td>
          <td>{{ obj.type }}</td>
          <td>{{ obj.state }}</td>
          <td> 
          <a href="{% url "accounting_finance:accounting_account_tree" %}" class="btn btn-info">Test</a>
          <a href="{% url "accounting_finance:accounting_account_edit" %}?accounts_plan={{ accounts_plan.pk }}&accounting_account={{ obj.id }}" class="btn btn-info">Edit</a> |
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

<!-- Pagination controls -->
{% include 'snippets/pagination.html' %}

{% endblock %}

apps/accounting_finance/templates/accounting_period_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Período contable
{% endblock %}

{% block heading %}

{% for message in messages %}
    <div class = "alert alert-{{ message.tags }} alert-dismissable">
       <button type = "button" class = "close" data-dismiss = "alert" aria-hidden = "true">
          &times;
       </button>
       {{ message }}
    </div>

{% endfor %}

<h5> Periódos contables </h5>
<p><a  href="{% url "accounting_finance:accounting_period_create" %}" class="btn btn-info">Nuevo</a></p>
<hr style="width: 100%; color: black; height: 1px; background-color:black;" />

{% endblock %}

{% block content %}
<!-- Output table -->
  <div class="row">
    <table class="table table-striped table-hover" cellpadding=0 cellspacing=10>
      <thead>
        <tr>
          <th>Código</th>
          <th>Año</th>
          <th>Estado</th>
          <th>Acciones</th>
          <th>Plan de cuentas</th>
          <th>Clasificador presupuestario</th>
        </tr>
      </thead>
      <tbody>
      {% for obj in object_list %}
        <tr>
          <td>{{ obj.code }}</td>
          <td>{{ obj.year }}</td>
          <td>{{ obj.get_state_display }}</td>
          <td>
              <a href="{% url "accounting_finance:accounting_period_detail" obj.id %}">Ver</a> |
              <a href="{% url "accounting_finance:accounting_period_edit" obj.id %}">Editar</a> |
              <a class="text-danger" id="accounting-period-{{ obj.id }}"
                        href="#" data-form="/accounting_finance/accounting_period/delete/" title="Crear">Eliminar</a>
          </td>
          <td>
            <a href="{% url "accounting_finance:accounts_plan_all" %}?accounting_period={{  obj.id }}">Ver</a>
          </td>
          <td>
            <a href="#">Ver</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>

<!-- Pagination controls -->
{% include 'snippets/pagination.html' %}


  <!-- Modal -->
  <div class="modal fade" id="delete-confirm-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header modal-header-primary">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Información</h4>
        </div>
        <div class="modal-body">
          <p>Está seguro que desea eliminar el período contable seleccionado?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <a href="#" id="delete-confirm-btn" class="btn btn-danger"><i class="icon-trash"></i>Aceptar</a>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock %}

{% block javascript %}
  <script>
    $("a[id^=accounting-period]").click(function(ev) { // for each edit knowledge url
        console.log('intro del activity');
        ev.preventDefault(); // prevent navigation
        var accounting_period_id = $(this).attr('id').split('-')[2];
        var url = $(this).data("form");
        console.log('>>> ' + accounting_period_id);
        BootstrapDialog.show({
            type: BootstrapDialog.TYPE_SUCCESS,
            title: 'Confirmar',
            message: 'Está seguro que desea eliminar el registro',
            closable: false,
            buttons: [ {
                label: 'Aceptar',
                action: function(dialog){
                    $.ajax({
                        type: 'DELETE', // http method
                        url: url, // get the knowledge form url
                        data : {accounting_period_id: accounting_period_id}, // data sent with the delete request
                        context: this,
                        success: function(data, status) {
                            console.log("deletion successful");
                            console.log(data);
                            console.log('>>>');
                            dialog.close();
                            window.location="/apps/accounting_finance/accounting_period/all/";
                        },
                        error: function(data, status) {
                            console.log("deletion error");
                            console.log(data);
                            console.log('>>>');
                            dialog.close();
                            window.location="/apps/accounting_finance/accounting_period/all/";
                        },
                        headers: {'X-HTTP-Method-Override': 'DELETE' }
                    });
                }
            }, {
                label: 'Cerrar',
                action: function(dialog){
                    dialog.close();
                }
            }]
        });
        return false; // prevent the click propagation
    });

     function getCookie(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie != '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
                var cookie = jQuery.trim(cookies[i]);
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) == (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    var csrftoken = getCookie('csrftoken');

    function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }

   $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
    });


  </script>
{% endblock %}

apps/accounting_finance/templates/accounts_plan_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Plan de cuentas:
{% endblock %}

{% block heading %}

{% for message in messages %}
    <div class = "alert alert-{{ message.tags }} alert-dismissable">
       <button type = "button" class = "close" data-dismiss = "alert" aria-hidden = "true">
          &times;
       </button>

        {% if message.tags == "success" %}
          <strong>Correcto!</strong> {{ message }}
        {% endif %}

        {% if message.tags == "danger" %}
          <strong>Error!</strong> {{ message }}
        {% endif %}

    </div>

  {% endfor %}

<h5> Plan de cuentas </h5>
<p>
  <a  href="{% url "accounting_finance:accounts_plan_create" %}?accounting_period={{  accounting_period.pk }}" class="btn btn-info">Nuevo</a>
  <a  href="{% url "accounting_finance:accounting_period_all" %}" class="btn btn-info pull-right">Regresar</a>
</p>

<hr style="width: 100%; color: black; height: 1px; background-color:black;" />
{% endblock %}

{% block content %}
<!-- Output table -->
  <div class="row">
    <table class="table table-striped table-hover" cellpadding=0 cellspacing=10>
      <thead>
        <tr>
          <th>Código</th>
          <th>Nombre</th>
          <th>Estado</th>
          <th>Acciones</th>
          <th>Cuentas contables</th>
        </tr>
      </thead>
      <tbody>
      {% for obj in object_list %}
        <tr>
          <td>{{ obj.code }}</td>
          <td>{{ obj.name }}</td>
          <td>{{ obj.get_state_display }}</td>
          <td>
               <a href="{% url "accounting_finance:accounts_plan_detail" %}">Ver</a> |
              <a href="{% url "accounting_finance:accounts_plan_edit" %}?accounting_period={{ accounting_period.pk }}&accounts_plan={{  obj.id }}" class="btn btn-info">Editar</a> |
              <a class="delete-btn btn btn-danger" id="del-accounts-plan-{{ obj.id }} "
                href="{% url "accounting_finance:accounts_plan_delete" obj.id %}">Eliminar</a>
          </td>
          <td>
            <a style="display:none" href="{% url "accounting_finance:accounting_account_all" %}?accounts_plan={{ obj.id }}">Ver</a>
            <a href="{% url "accounting_finance:accounting_account_tree" %}?accounts_plan={{ obj.id }}" class="btn btn-info">Visualizar</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>




<!-- Pagination controls -->
{% if object_list|length > 0  %}
  {% if is_paginated %}
    <nav>
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li>
            <a href="?accounting_period={{ accounting_period.pk }}&page={{ page_obj.previous_page_number }}">
              <span>Previous</span>
            </a>
          </li>
        {% else %}
          <li class="disabled">
            <a href="#">
              <span>Previous</span>
            </a>
          </li>
        {% endif %}

        {% for page in paginator.page_range %}
          <li {% if page == page_obj.number %}class="active"{% endif %}>
            <a href="?accounting_period={{ accounting_period.pk }}&page={{ page }}">{{ page }}</a>
          </li>
        {% endfor %}

        {% if page_obj.has_next %}
          <li>
            <a href="?accounting_period={{ accounting_period.pk }}&page={{ page_obj.next_page_number }}">
              <span>Next</span>
            </a>
          </li>
        {% else %}
          <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
            <a href="#">
              <span>Next</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
  {% endif %}

{% endif %}



 <!-- Modal -->
  <div class="modal fade" id="delete-confirm-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header modal-header-primary">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Información</h4>
        </div>
        <div class="modal-body">
          <p>Está seguro que desea eliminar el plan de cuentas seleccionado?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <a href="#" id="delete-confirm-btn" class="btn btn-danger"><i class="icon-trash"></i>Aceptar</a>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

{% endblock %}

{% block javascript %}

  <script type="text/javascript">

  $(".delete-btn").click(function() {
    console.log(">>> intro delete-bnt");
    $("#delete-confirm-btn").attr("href", $(this).attr("href"));
    $("#delete-confirm-modal").modal('toggle');
    return false;
  });

  </script>


{% endblock %}

apps/accounting_finance/templates/accounts_plan_list_tmp.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
  Plan de cuentas
{% endblock %}

{% block heading %}

<h5> Plan de cuentas </h5>
<p><a  href="{% url "accounting_finance:accounts_plan_create" %}?accounting_period={{  accounting_period.pk }}" class="btn btn-info">Nuevo</a></p>
<hr style="width: 100%; color: black; height: 1px; background-color:black;" />
{% endblock %}

{% block content %}
<!-- Output table -->
  <div class="row">
    <table class="table table-striped table-hover" cellpadding=0 cellspacing=10>
      <thead>
        <tr>
          <th>Código</th>
          <th>Nombre</th>
          <th>Estado</th>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
      {% for obj in object_list %}
        <tr>
          <td>{{ obj.code }}</td>
          <td>{{ obj.name }}</td>
          <td>{{ obj.state }}</td>
          <td>
              <a href="{% url "accounting_finance:accounts_plan_detail" %}">Ver</a> |
              <a href="{% url "accounting_finance:accounts_plan_edit" %}">Editar</a> |
              <a href="{% url "accounting_finance:accounts_plan_edit" %}?accounting_period={{ accounting_period.pk }}&accounts_plan={{  obj.id }}" class="btn btn-info">Edit</a> |

              <a href="{% url "accounting_finance:accounts_plan_delete" %}">Borrar</a>
          </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
  </div>
  <div class="row">
    <p><a  href="{% url "accounting_finance:accounting_period_all" %}" class="btn btn-info">Regresar</a></p>
  </div>

<!-- Pagination controls -->


<!-- Pagination controls -->
{% if is_paginated %}
  <nav>
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li>
          <a href="?accounting_period={{ accounting_period.pk }}&page={{ page_obj.previous_page_number }}">
            <span>Previous</span>
          </a>
        </li>
      {% else %}
        <li class="disabled">
          <a href="#">
            <span>Previous</span>
          </a>
        </li>
      {% endif %}

      {% for page in paginator.page_range %}
        <li {% if page == page_obj.number %}class="active"{% endif %}>
          <a href="?accounting_period={{ accounting_period.pk }}&page={{ page }}">{{ page }}</a>
        </li>
      {% endfor %}

      {% if page_obj.has_next %}
        <li>
          <a href="?accounting_period={{ accounting_period.pk }}&page={{ page_obj.next_page_number }}">
            <span>Next</span>
          </a>
        </li>
      {% else %}
        <li {% if not page_obj.has_next %}class="disabled"{% endif %}>
          <a href="#">
            <span>Next</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}


{% endblock %}