apps/person/urls.py
from django.conf.urls import url

from .views import (
    person_create,
    person_list,
    person_update,
    person_delete,
    PersonDetail,
)


urlpatterns = [
    url(r'^$', person_list, name='person_list'),
    url(r'^detail/(?P<pk>\d+)$', PersonDetail.as_view(), name='person_detail'),
    url(r'^new$',person_create, name='person_new'),
    url(r'^edit/(?P<pk>\d+)$', person_update, name='person_edit'),
    url(r'^delete/(?P<pk>\d+)$', person_delete, name='person_delete'),
]

humanresource/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.urlresolvers import reverse_lazy
# from apps.institution import views
# from apps.schedule import views
# from apps.person import views
# from apps.contract import views
# from apps.accounts import views
from django.contrib.auth import login, logout
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.security.urls')),
    url(r'^evaluation/', include('apps.evaluation.urls', namespace='evaluation')),
    url(r'^accounting_finance/', include('apps.accounting_finance.urls', namespace='accounting_finance')),
    url(r'^catalogo/', include('apps.settings.urls', namespace='catalogo')),
    url(r'^institution/', include('apps.institution.urls', namespace='institution')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^roles/', include('apps.roles.urls', namespace='roles')),
    url(r'^partidas/', include('apps.partidas.urls', namespace='partidas')),
    url(r'^schedule/', include('apps.schedule.urls', namespace='schedule')),
    url(r'^person/', include('apps.person.urls', namespace='person')),
    url(r'^contract/', include('apps.contract.urls', namespace='contract')),
    url(r'^employee/', include('apps.employee.urls', namespace='employee')),
    url(r'^vacacion/', include('apps.vacacion.urls', namespace='vacacion')),
    url(r'^cambios/', include('apps.cambios.urls', namespace='cambios')),
    url(r'^curriculum/', include('apps.curriculum.urls', namespace='curriculum')),
    url(r'^personnelactions/', include('apps.personnel_actions.urls', namespace='personnelactions')),
    url(r'^economicdata/', include('apps.economicdata.urls', namespace='economicdata')),
    url(r'^permissions/', include('apps.permissions.urls', namespace='permissions')),
    url(r'^login/$', login, {'template_name': 'app/login.html'}, name='security_login'),
    url(r'^logout/$', logout, {'next_page': reverse_lazy('security_main')}, name='security_logout'),

]
# urlpatterns += staticfiles_urlpatterns()

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Municipio de Loja'

apps/person/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from apps.settings.models import Catalog
from apps.settings.models import Item

from django.db import models


# Create your models here.
class Person(models.Model):
    # -------------Tipo de Documento---------------
    pasaporte = 'pasaporte'
    ci = 'cedula'
    document_type_list = (
        (ci, 'Cédula'),
        (pasaporte, 'Pasaporte'),
    )

    # catalog = Catalog.objects.get(pk=1)
    # items = Item.objects.filter(catalog='SEXO')
    # GENERO_CHOICES = tuple([(item.name,item.name) for item in items])



    document_type = models.CharField(verbose_name='Tipo de Documento', max_length=9, choices=document_type_list,
                                     default=ci, blank=True, null=True)
    cedula = models.CharField(verbose_name='# Documento de Identificación', unique=True, max_length=13)
    name = models.CharField(verbose_name='Nombres', max_length=100)
    lastname = models.CharField(verbose_name='Apellidos', max_length=100)
    photo = models.ImageField(upload_to='albums/images/', verbose_name='Fotografía', blank=True, null=True)
    sex = models.ForeignKey(Item, on_delete=models.PROTECT, limit_choices_to={'catalog__code': 'SEXO'}, max_length=10,
                            verbose_name='Sexo', blank=True, null=True)
    country = models.ForeignKey(Item, on_delete=models.PROTECT, limit_choices_to={'catalog__code': 'PAIS', },
                                max_length=25, verbose_name='Pais', blank=True, null=True, related_name='catalog_pais')
    province_of_residence = models.CharField(verbose_name='Provincia de residencia', max_length=50, blank=True,
                                             null=True)
    canton_of_residence = models.CharField(verbose_name='Cantón de residencia', max_length=50, blank=True, null=True)
    parroquia_of_residence = models.CharField(verbose_name='Parroquia de residencia', max_length=50, blank=True,
                                              null=True)
    address = models.TextField(verbose_name='Dirección', max_length=300, blank=True, null=True)
    reference_address = models.TextField(verbose_name='Referencia', max_length=300, blank=True, null=True)
    province_of_birth = models.CharField(verbose_name='Provincia de nacimiento', max_length=50, blank=True, null=True)
    canton_of_birth = models.CharField(verbose_name='Cantón de nacimiento', max_length=50, blank=True, null=True)
    parroquia_of_birth = models.CharField(verbose_name='Parroquia de nacimiento', max_length=50, blank=True, null=True)
    place_of_birth = models.CharField(verbose_name='Lugar de nacimiento', max_length=100, blank=True, null=True)
    birthdate = models.DateField(verbose_name='Fecha de nacimiento', blank=True, null=True)
    civil_status = models.ForeignKey(Item, on_delete=models.PROTECT, limit_choices_to={'catalog__code': 'ESTADO CIVIL'},
                                     max_length=25, verbose_name='Estado civil', blank=True, null=True,
                                     related_name='catalog_civil_status')
    avatar = models.BooleanField(default=False, blank=True)
    phone = models.CharField(verbose_name='Teléfono', max_length=50, blank=True, null=True)
    cell_phone = models.CharField(verbose_name='Celular', max_length=10, blank=True, null=True)
    email = models.EmailField(verbose_name='Correo electrónico', max_length=100, blank=True, null=True)
    blood_type = models.ForeignKey(Item, on_delete=models.PROTECT, limit_choices_to={'catalog__code': 'TIPO DE SANGRE'},
                                   verbose_name='Tipo de sangre', blank=True, null=True,
                                   related_name='catalog_blood_type')

    disability_has = models.BooleanField(verbose_name='Posee alguna discapacidad', default=False)
    disability = models.ForeignKey(Item, on_delete=models.PROTECT, limit_choices_to={'catalog__code': 'DISCAPACIDAD'},
                                   verbose_name='Discapacidad', blank=True, null=True,
                                   related_name='catalog_disability')
    percentage_of_disability = models.IntegerField(verbose_name='Porcentaje de discapacidad', blank=True, null=True)
    is_has_catastrophic_illness = models.BooleanField(verbose_name='Posee alguna enfermedad catastrófica',
                                                      default=False)
    catastrophic_illness = models.CharField(verbose_name='Enfermedad catastrófica', max_length=200, blank=True,
                                            null=True)
    substitute = models.BooleanField(verbose_name='Es sustituto', default=False)
    family_identity_card = models.CharField(verbose_name='Cédula del familiar', max_length=13, blank=True, null=True)
    family_name = models.CharField(verbose_name='Nombre del familiar', max_length=100, blank=True, null=True)
    family_type_of = models.ForeignKey(Item, on_delete=models.PROTECT,
                                       limit_choices_to={'catalog__code': 'DISCAPACIDAD'},
                                       verbose_name='Tipo de discapacidad del familiar', blank=True, null=True,
                                       related_name='catalog_family_type_of')
    porcentage_of_family_disability = models.IntegerField(verbose_name='Porcentaje de discapacidad del familiar',
                                                          blank=True, null=True)
    relationship = models.ForeignKey(Item, on_delete=models.PROTECT, limit_choices_to={'catalog__code': 'PARENTESCO'},
                                     verbose_name='Parentesco', blank=True, null=True,
                                     related_name='catalog_relationship')

    class Meta:
        # ordering = ['lastname', 'name', 'cedula']
        verbose_name = 'Persona'
        verbose_name_plural = 'Personas'

    def __str__(self):
        return u'{0}-{1}-{2}'.format(self.name,self.lastname, self.cedula)

    def __unicode__(self):
        return u'{0}-{1}-{2}'.format(self.name,self.lastname,  self.cedula)

apps/person/forms.py
from django import forms
from django.forms import ModelForm
from .models import Person
from apps.settings.models import Catalog, Item


# class PersonForm(ModelForm):
#	class Meta:
#		model = Person
#		fields = '__all__'
#		exclude = ('id',)

#		self.fields['institutional_unit'].queryset = InstitutionalUnit.objects.filter(institution=institution)


class PersonForm(ModelForm):
    def clean(self):
        cleaned_data = super(PersonForm, self).clean()

        name = cleaned_data.get("name")
        if name == None:
            self.add_error('name', 'Nombre debe contener al menos 3 caracteres!')
        elif len(name) < 3:
            self.add_error('name', 'Nombre debe contener al menos 3 caracteres!')

        cedula = cleaned_data.get("cedula")
        if cedula == None:
            self.add_error('cedula', 'Cédula debe contener 10 o 13 caracteres!')
        elif len(cedula) < 10 and len(cedula) <= 13:
            self.add_error('cedula', 'Cédula debe contener 10 o 13 caracteres!')

        lastname = cleaned_data.get("lastname")
        if lastname == None:
            self.add_error('lastname', 'Apellido debe contener al menos 3 caracteres!')
        elif len(lastname) < 3:
            self.add_error('lastname', 'Apellido debe contener al menos 3 caracteres!')

        return cleaned_data

    # def __init__(self, *args, **kwargs):

    #	catalog = Catalog.objects.get(pk=2)
    #	super (PersonForm, self ). __init__(*args, **kwargs)
    #	self.fields['sex'].queryset = forms.ModelChoiceField(queryset = Item.objects.filter(catalog=2))



    class Meta:
        model = Person
        fields = '__all__'
        exclude = ('id',)
        widgets = {
            'birthdate': forms.DateInput(attrs={'class': 'datepicker', 'placeholder':'día/mes/año: ( 29/03/2017 )' }),
        }

apps/person/views.py
# -*- coding: utf-8 -*-
from django.db import transaction, IntegrityError, OperationalError
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators  import  login_required
from django.shortcuts import render
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from apps.person.models import Person

from apps.institution.models import Institucion, JefaturaCoordinacion, Directivo, Direccion
# from apps.institution.models import Institution, InstitutionalUnit, Department
from apps.curriculum.models import CurriculumVitae, FormalInstruction, OfficesOrsubactivities,Language,Training,WorkExperience,PerformanceEvaluation,PersonalAchievement,AffirmativeAction,PersonalReferences
from .forms import PersonForm
from apps.employee.models import Employee
from apps.curriculum.models import CurriculumVitae, AffirmativeAction
from django.db.models import Q
from django.contrib import messages
from apps.accounts.models import UserProfile
# from apps.institution.models import Institution
# Create your views here.
#-----------Persona-----------
@login_required()
def person_list(request, template_name='person/person_list.html'):
    person = Person.objects.all()
    data = {}
    query = request.GET.get('q', '')
    if query == '':
        person = Person.objects.all()
        paginator = Paginator(person, 10) # Show 25 contract per page
        page = request.GET.get('page')

        try:
            persons = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            persons = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            persons = paginator.page(paginator.num_pages)

    else:

        if query:
            qset = (
                Q(name__icontains=query) |
                Q(lastname__icontains=query) |
                Q(cedula__icontains=query)
            )
            person = Person.objects.filter(qset).distinct()
            paginator = Paginator(person, 10) # Show 25 contract per page
            page = request.GET.get('page')

            try:    
                persons = paginator.page(page)
            except PageNotAnInteger:
            # If page is not an integer, deliver first page.
                persons = paginator.page(1)
            except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
                persons = paginator.page(paginator.num_pages)
        else:
            persons = []

    data['object_list'] = persons
    data['query'] = query
    return render(request, template_name, data)


@login_required()
@transaction.atomic
def person_create(request, template_name='person/person_form.html'):
    user_profile_autent = UserProfile.objects.get(user=request.user) #Obtengo el perfil del cedula donde esta autenticado
    institution = user_profile_autent.institution_default   #Obtengo la institucion por defecto del cedula autenticado
    form = PersonForm(request.POST or None)
    sp1 = transaction.savepoint()
    try:
        if form.is_valid():
            form.save()
            #messages.add_message(request, messages.INFO, 'Persona Agregada Correctamente.')
            person = get_object_or_404(Person, cedula=request.POST.get('cedula'))
            employee, created = Employee.objects.get_or_create(person=person,institution=institution)        
            curriculum_vitae, created = CurriculumVitae.objects.get_or_create(person=person)
            curriculum = CurriculumVitae.objects.get(person=person)
            affirmativeaction = AffirmativeAction.objects.create(curriculum_vitae=curriculum, hero=False, former_fighter=False, ecuadorian_migrant=False)
            transaction.savepoint_commit(sp1)
            messages.success(request, 'Buen Trabajo. Datos ingresados correctamente.')
            return redirect('employee:employee_edit' ,pk=employee.pk)
            # return redirect('person:person_list')
        

    except Exception as e:
        messages.error(request, 'Tuvimos un problema. Los Datos no han sido almacenados.')
        print (e)
        #messages.add_message(request, messages.ERROR, 'Los Datos no han sido almacenados')
        transaction.savepoint_rollback(sp1)
        return redirect('person:person_list')
    finally:
        Final="Todas las operaciones ejecutadas con exito"
    
    return render(request, template_name, {'form':form})


@login_required()
def person_update(request, pk, template_name='person/person_form.html'):
    person = get_object_or_404(Person, pk=pk)
    form = PersonForm(request.POST or None, instance=person)
    if form.is_valid():
        form.save()
        messages.info(request, 'Buen Trabajo. Datos actualizados correctamente.')
        return redirect('person:person_list')
    return render(request, template_name, {'form':form})

@login_required()
def person_delete(request, pk):
    try:
        person = get_object_or_404(Person, pk=pk)    
        person.delete()
        messages.success(request, 'Bien. Los datos han sido eliminados correctamente.')
    
    except Exception as inst:
        
        messages.error(request, 'Error. Los datos no se han podido eliminar. Verificar que la persona no tenga información asociada como Currículo o Contratos')

    return redirect('person:person_list')
    




class PersonDetail(DetailView):
    model = Person

apps/person/templates/person/employee_detail.html
{% extends "base.html" %}

{% block heading %}

     {% include "person/menu_employee.html" %}    
{% endblock %}
{% block content %}


<div class="panel panel-primary" id="datos_personales">
    <div class="panel-heading">
        <h3 class="panel-title"><b>Datos Personales</b></h3>
    </div>
    <div class="panel-body">
        {% include "person/datos_personales_detail.html" %}   
    </div>
</div>

<div class="panel panel-primary"  id="curriculo">
    <div class="panel-heading">
        <h3 class="panel-title"><b>Currículo</b></h3>
    </div>
    <div class="panel-body">              
        {% include "person/curriculo_detail.html" %}                      
    </div>                           
</div>

<div class="panel panel-primary"  id="curriculo2">
    <div class="panel-heading">
        <h3 class="panel-title"><b>Datos Económicos</b></h3>
    </div>
    <div class="panel-body">              
        {% include "person/curriculo_detail.html" %}                      
    </div>                           
</div>


   

    
   
 
         
{% endblock %}

apps/person/templates/person/person_confirm_delete.html
{% extends "base.html" %}
{% block content %}    
    <form method="post">{% csrf_token %}
        ¿Estás seguro que deseas borrar a: "{{ object }}"?
        <input type="submit" value="Eliminar" />
    </form>
{% endblock %}

apps/person/templates/person/person_form_2.html
{% extends "base.html" %}
{% load contrato_templatetags %}
{% block content %}

<div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        Personas
      </h1>
      <ol class="breadcrumb">
        <li>
          <i class="fa fa-dashboard"></i>  <a href="/">Inicio</a>
        </li>
        <li class="active">
          <i class="fa fa-edit"></i> <a href="{% url "person:person_list" %}"> Personas</a>
        </li>
        <li class="active">
          <i class="fa fa-edit"></i> Agregar o Editar Persona
        </li>
        
       </ol>
    </div>
</div>

<form class="form-horizontal" method="post">
  {% csrf_token %}
  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.errors }}
      <label class="col-sm-2 control-label" for="{{ field.name }}">{{ field.label }}</label>
      <div class="col-sm-8">
        {{ field|addclass:'form-control' }}
      </div>
    </div>
  {% endfor %}
  
  <div class="col-lg-12" >
    <div class="btn-group" role="group" >
      <button type="submit" class="btn btn-success">Guardar</button>
      <a href="{% url "person:person_list" %}" class="btn btn-success" role="button">Cancelar</a>
                   
    </div>
  </div>
</form>

{% endblock %}

{% block javascript %}
   <script>
      var start_date=$('input[name="birthdate"]'); //our date input has the name "date"
      var options={
          format: 'mm/dd/yyyy',
          orientation:"bottom",
          todayHighlight: true,
          autoclose: true,
          language: "es",
      };
      start_date.datepicker(options); //initiali110/26/2015 8:20:59 PM ze plugin
      var end_date=$('input[name="birthdate"]'); //our date input has the name "date"
      end_date.datepicker(options); //initiali110/26/2015 8:20:59 PM ze plugin
    
    function muestra_oculta(id){
      if (document.getElementById){ //se obtiene el id
      var el = document.getElementById(id); //se define la variable "el" igual a nuestro div
      el.style.display = (el.style.display == 'none') ? 'block' : 'none'; //damos un atributo display:none que oculta el div
    }

    
    </script>
{% endblock %}

apps/person/templates/person/person_list.html
{#{% extends "base.html" %}#}
{% extends "app/base_site.html" %}
{% block stylesheets %}
    {{ block.super }}
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">
{% endblock stylesheets %}

{% block content %}

{#<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.11/css/jquery.dataTables.css">#}

 <div class="right_col" role="main">

        {% block heading %}

            <div class="row">
                <div class="col-lg-12">
                    <h2 class="page-header">
                        PERSONAS
                    </h2>
                    <ol class="breadcrumb">
                        <li>
                            <i class="fa fa-home"></i>  <a href="/">Inicio</a>
                        </li>
                        <li class="active">
                            <i class="fa fa-users"></i>Personas
                        </li>

                    </ol>
                </div>
            </div>
            <div class="col-lg-4">#}
                <a href="{% url "person:person_new" %}">Agregar Persona</a>
            </div>
        {% endblock %}



{#    <div class="row">#}
{#    <div class="col-lg-4">#}
{#            <a href="{% url "person:person_new" %}">Agregar Persona</a>#}
{#    </div>#}
{#    <div class="col-lg-8">#}
{#        <form action="" method="GET">#}
{#            <div class="col-lg-12">#}
{#                <div class="form-group input-group">#}
{#                    <input id="busquedProyecto" type="text" name="q" value="{{ query|escape }}" class="form-control">#}
{#                    <span class="input-group-btn"><button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button></span>#}
{##}
{#                </div>#}
{#            </div>#}
{#        </form>#}
{##}
{#    </div>#}
{#</div>#}






        <div class="">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                <div class="x_content">
{#                        <p class="text-muted font-13 m-b-30">#}
{#                            The Buttons extension for DataTables provides a common set of options, API methods and#}
{#                            styling to display buttons on a page that will interact with a DataTable. The core library#}
{#                            provides the based framework upon which plug-ins can built.#}
{#                        </p>#}
                        <table id="datatable-buttons" class="table table-striped table-bordered">

{#    <div class="table-responsive">#}

{#    <table id="table_instituciones" class="table table-bordered table-hover table-striped">#}
    <thead>
        <tr>
            <th>Cédula</th>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Acciones</th>

        </tr>
    </thead>
    <tbody>
    {% for person in object_list %}
        {# Each "contact" is a Contact model object. #}
        <tr>
            <td>{{ person.cedula }} </td>
            <td>{{ person.name }} </td>
            <td>{{ person.lastname }} </td>
            <td>
                <div class="btn-group" dropdown>
                    <button type="button" class="btn btn-warning"><span class="glyphicon glyphicon-list"></span></button>
                    <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown">
                        <span class="caret"></span>
                        <span class="sr-only">Split button!</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url "person:person_detail" person.id  %}">Ver</a></li>
                        <li><a href="{% url "person:person_edit" person.id %}">Editar</a></li>
                        <li><a href="#" data-toggle="modal" data-target="#object{{person.id}}">Borrar</a></li>
                    </ul>
                </div>
            </td>
        </tr>
         <!-- Modal -->
      <div class="modal fade" id="object{{person.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header modal-header-primary">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">Información</h4>
            </div>

                <div class="modal-body">
                     <p>Está seguro que desea eliminar la persona: {{ person }}?</p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                  <a href="{% url "person:person_delete" person.id %}" id="delete-confirm-btn" class="btn btn-danger" type="submit"><i class="icon-trash"></i>Aceptar</a>

                </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    {% endfor %}
    </tbody>
</table>
</div>
    </div>
            </div></div></div>


{% endblock %}


{% block javascripts %}
    {{ block.super }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    {#<script src="/static/vendors/datatables.net-buttons/js/dataTables.buttons.min.js"></script>#}
    <script src="/static/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js"></script>
    {#<script src="/static/vendors/datatables.net-buttons/js/buttons.flash.min.js"></script>#}
    {#<script src="/static/vendors/datatables.net-buttons/js/buttons.html5.min.js"></script>#}
    {#<script src="/static/vendors/datatables.net-buttons/js/buttons.print.min.js"></script>#}
    <script src="/static/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js"></script>
    <script src="/static/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive/js/dataTables.responsive.min.js"></script>
    <script src="/static/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js"></script>
    <script src="/static/vendors/datatables.net-scroller/js/dataTables.scroller.min.js"></script>
    {#<script src="/static/vendors/jszip/dist/jszip.min.js"></script>#}
    <script src="/static/vendors/pdfmake/build/pdfmake.min.js"></script>
    {#<script src="/static/vendors/pdfmake/build/vfs_fonts.js"></script>#}
    {#Scripts para llamar los reportes de tablas#}
    <script src="/static/vendors/ScriptsDataTable/buttons.flash.min.js"></script>
    <script src="/static/vendors/ScriptsDataTable/buttons.html5.min.js"></script>
    <script src="/static/vendors/ScriptsDataTable/buttons.print.min.js"></script>
    <script src="/static/vendors/ScriptsDataTable/dataTables.buttons.min.js"></script>
    <script src="/static/vendors/ScriptsDataTable/jszip.min.js"></script>
    <script src="/static/vendors/ScriptsDataTable/pdfmake.min.js"></script>
    <script src="/static/vendors/ScriptsDataTable/vfs_fonts.js"></script>
{% endblock javascripts %}