apps/institution/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

from .views import (

    listar_institucion,
    # listar_institucion_inactiva,
    crear_institucion,
    actualizar_institucion,
    eliminar_institucion,
    dar_baja_institucion,
    ver_institucion,
    listar_coordinacion,
    ver_coordinacion,
    crear_coordinacion,
    actualizar_coordinacion,
    eliminar_coordinacion,

    listar_directivo,
    crear_directivo,
    actualizar_directivo,
    ver_directivo,

    listar_direccion,
    crear_direccion,
    actualizar_jefatura,
    eliminar_jefatura,
    ver_direccion,

    # DirectivoDetail,
    institution_list_user,
    institution_create_user,
    institution_update_user,
    institution_delete_user,
    institution_detail_user,
    institutional_unit_list_user,
    institutional_unit_create_user,
    institutional_unit_update_user,
    institutional_unit_delete_user,
    institutional_unit_detail_user,
    department_create_user,
    department_list_user,
    department_delete_user,
    department_update_user,

    crear_coordinacion2)

urlpatterns = [

    # urls admin
    # urls instituciones
    url(r'^admin/$', listar_institucion, name='institution_list'),
    # url(r'^admin/$', listar_institucion, name='institution_list'),
    # url(r'^admin/inactivas$', listar_institucion_inactiva, name='institution_list_inactive'),
    url(r'^admin/new$', crear_institucion, name='institution_new'),
    url(r'^admin/editar/(?P<pk>\d+)$', actualizar_institucion, name='institution_edit'),
    url(r'^admin/borrar/(?P<pk>\d+)/(?P<estado>\d+)/$', eliminar_institucion, name='institution_delete2'),
    url(r'^admin/borrar/(?P<pk>\d+)$', dar_baja_institucion, name='institution_delete'),
    url(r'^admin/(?P<pk>\d+)$', ver_institucion, name='institution_detail'),
    # urls direcciones
    # url(r'^admin/institutionalunit$', listar_directivo, name='institutionalunit_list'),
    # url(r'^admin/institutionalunit/(?P<pk>\d+)$', ver_directivo, name='institutionalunit_detail'),
    # url(r'^admin/direccioninstitucional2/(?P<pk>\d+)$', DirectivoDetail.as_view(), name='direccioninstitucional_detail2'),

    # url(r'^admin/direccioninstitucional/edit/(?P<pk>\d+)$', actualizar_directivo, name='direccioninstitucional_edit'),

    url(r'^admin/directivo$', listar_directivo, name='directivo_listar'),
    url(r'^admin/directivo/(?P<pk>\d+)$', ver_directivo, name='directivo_ver'),
    # url(r'^admin/direccioninstitucional2/(?P<pk>\d+)$', DirectivoDetail.as_view(), name='direccioninstitucional_detail2'),
    url(r'^admin/directivo/new$', crear_directivo, name='directivo_nuevo'),
    url(r'^admin/directivo/edit/(?P<pk>\d+)$', actualizar_directivo, name='directivo_editar'),

    url(r'^admin/direccion$', listar_direccion, name='direccion_listar'),
    url(r'^admin/direccion/detail/(?P<pk>\d+)$', ver_direccion, name='direccion_ver'),
    url(r'^admin/direccion/new$', crear_direccion, name='direccion_nuevo'),

    url(r'^admin/direccion/edit/(?P<pk>\d+)$', actualizar_jefatura, name='direccion_editar'),
    url(r'^admin/jefatura/delete/(?P<pk>\d+)$', eliminar_jefatura, name='jefatura_delete'),

    # Codigo nuevo
    url(r'^admin/coordinacion$', listar_coordinacion, name='coordinacion_list'),
    url(r'^admin/coordinacion/detail/(?P<pk>\d+)$', ver_coordinacion, name='coordinacion_detail'),
    url(r'^admin/coordinacion/new$', crear_coordinacion, name='coordinacion_new'),
    url(r'^admin/coordinacion2/new/(?P<id>\d+)$', crear_coordinacion2, name='coordinacion_new2'),
    url(r'^admin/coordinacion/edit/(?P<pk>\d+)$', actualizar_coordinacion, name='coordinacion_edit'),
    url(r'^admin/coordinacion/delete/(?P<pk>\d+)$', eliminar_coordinacion, name='coordinacion_delete'),

    # Fin codigo nuevo


    # urls user

    url(r'^$', institution_list_user, name='institution_list_user'),
    url(r'^new$', institution_create_user, name='institution_new_user'),
    url(r'^(?P<pk>\d+)$', institution_detail_user, name='institution_detail_user'),
    url(r'^editar/(?P<pk>\d+)$', institution_update_user, name='institution_edit_user'),
    url(r'^borrar/(?P<pk>\d+)$', institution_delete_user, name='institution_delete_user'),

    url(r'^institutionalunit$', institutional_unit_list_user, name='institutionalunit_list_user'),
    url(r'^institutionalunit/new$', institutional_unit_create_user, name='institutionalunit_new_user'),
    url(r'^institutionalunit/(?P<pk>\d+)$', institutional_unit_detail_user, name='institutionalunit_detail_user'),
    url(r'^institutionalunit/edit/(?P<pk>\d+)$', institutional_unit_update_user, name='institutionalunit_edit_user'),
    url(r'^institutionalunit/delete/(?P<pk>\d+)$', institutional_unit_delete_user,
        name='institutionalunit_delete_user'),

    url(r'^department$', department_list_user, name='department_list_user'),
    url(r'^department/new$', department_create_user, name='department_new_user'),
    url(r'^department/edit/(?P<pk>\d+)$', department_update_user, name='department_edit_user'),
    url(r'^department/delete/(?P<pk>\d+)$', department_delete_user, name='department_delete_user'),

]

apps/permissions/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url, include
from .views import (
    type_of_permit_list,
    type_of_permit_create,
    type_of_permit_update,
    type_of_permit_delete,

    permission_list_user,
    permission_user_create,
    permission_user_update,
    permission_user_delete,
)


urlpatterns = [

    #urls admin
    url(r'^admin/$', type_of_permit_list, name='type_of_permit_list'),
    url(r'^admin/new$', type_of_permit_create, name='type_of_permit_new'),
    url(r'^admin/editar/(?P<pk>\d+)$', type_of_permit_update, name='type_of_permit_edit'),      
    url(r'^admin/borrar/(?P<pk>\d+)$', type_of_permit_delete, name='type_of_permit_delete'),


    url(r'^$', permission_list_user, name='permission_list'),
    url(r'^new/(?P<cedula>\d+)$', permission_user_create, name='permission_new'),
    url(r'^editar/(?P<pk>\d+)$', permission_user_update, name='permission_edit'),      
    url(r'^borrar/(?P<pk>\d+)$', permission_user_delete, name='permission_delete'),
    #url(r'^admin/(?P<pk>\d+)$',institution_detail, name='institution_detail'),
    #url(r'^admin/2/(?P<pk>\d+)$',InstitutionDetail.as_view(), name='institution_detail2'),
    
    

    
]

humanresource/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.core.urlresolvers import reverse_lazy
# from apps.institution import views
# from apps.schedule import views
# from apps.person import views
# from apps.contract import views
# from apps.accounts import views
from django.contrib.auth import login, logout
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.security.urls')),
    url(r'^evaluation/', include('apps.evaluation.urls', namespace='evaluation')),
    url(r'^accounting_finance/', include('apps.accounting_finance.urls', namespace='accounting_finance')),
    url(r'^catalogo/', include('apps.settings.urls', namespace='catalogo')),
    url(r'^institution/', include('apps.institution.urls', namespace='institution')),
    url(r'^accounts/', include('apps.accounts.urls', namespace='accounts')),
    url(r'^roles/', include('apps.roles.urls', namespace='roles')),
    url(r'^partidas/', include('apps.partidas.urls', namespace='partidas')),
    url(r'^schedule/', include('apps.schedule.urls', namespace='schedule')),
    url(r'^person/', include('apps.person.urls', namespace='person')),
    url(r'^contract/', include('apps.contract.urls', namespace='contract')),
    url(r'^employee/', include('apps.employee.urls', namespace='employee')),
    url(r'^vacacion/', include('apps.vacacion.urls', namespace='vacacion')),
    url(r'^cambios/', include('apps.cambios.urls', namespace='cambios')),
    url(r'^curriculum/', include('apps.curriculum.urls', namespace='curriculum')),
    url(r'^personnelactions/', include('apps.personnel_actions.urls', namespace='personnelactions')),
    url(r'^economicdata/', include('apps.economicdata.urls', namespace='economicdata')),
    url(r'^permissions/', include('apps.permissions.urls', namespace='permissions')),
    url(r'^login/$', login, {'template_name': 'app/login.html'}, name='security_login'),
    url(r'^logout/$', logout, {'next_page': reverse_lazy('security_main')}, name='security_logout'),

]
# urlpatterns += staticfiles_urlpatterns()

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Municipio de Loja'

apps/permissions/models.py
from django.db import models
from apps.employee.models import Employee


# Create your models here.
class TypeOfPermit(models.Model):
    type_of_permit = models.CharField(verbose_name='Tipo de permiso', max_length=100)
    status = models.BooleanField(verbose_name='Estado', default=True)

    class Meta:
        ordering = ['type_of_permit']
        verbose_name = 'Tipo de permiso'
        verbose_name_plural = 'Tipos de permiso'

    def __str__(self):
        return u'{0}'.format(self.type_of_permit)

    def __unicode__(self):
        return u'{0}'.format(self.type_of_permit)


class Permission(models.Model):
    descuento_rol = 'descuento a rol'
    cargo_vacaciones = 'cargo a vacaciones'
    ninguna = 'ninguna'
    action_list = (
        (descuento_rol, 'Descuento a rol'),
        (cargo_vacaciones, 'Cargo a vacaciones'),
        (ninguna, 'Ninguna'),
    )

    employee = models.ForeignKey(Employee, verbose_name='Empleado', on_delete=models.PROTECT)
    type_of_permit = models.ForeignKey('TypeOfPermit', verbose_name='Tipo de Permiso', on_delete=models.PROTECT)
    action = models.CharField(verbose_name='Acción a ejecutar', choices=action_list, default=cargo_vacaciones,
                              max_length=50)
    registration_date = models.DateField(verbose_name='Fecha de registro')
    date_permiso = models.DateField(verbose_name='Fecha de permiso')
    start_time = models.TimeField(verbose_name='Hora de inicio')
    end_time = models.TimeField(verbose_name='Hora de fin')
    reason = models.TextField(verbose_name='Motivo')
    registered_by = models.CharField(verbose_name='Registrado por', max_length=100)

    class Meta:
        # ordering = ['employee', 'date_permiso']
        verbose_name = 'Permiso'
        verbose_name_plural = 'Permisos'

    def __str__(self):
        return u'{0}-{1}'.format(self.employee, self.type_of_permit)

    def __unicode__(self):
        return u'{0}-{1}'.format(self.employee, self.type_of_permit)

apps/permissions/forms.py
from django import forms
from django.forms import ModelForm, TextInput

from apps.employee.models import Employee
from .models import Permission, TypeOfPermit


class TypeOfPermitForm(ModelForm):
    class Meta:
        model = TypeOfPermit
        fields = '__all__'
        exclude = ('id',)


class PermissionForm(ModelForm):
    class Meta:
        model = Permission
        fields = '__all__'
        exclude = ('id',)


    def __init__(self, *args, **kwargs):
        # print(kwargs['cedula'])
        cedula = kwargs.pop('cedula')
        empleado_actual = Employee.objects.filter(person__cedula=cedula)
        super(PermissionForm, self).__init__(*args, **kwargs)
        self.fields['registration_date'].widget = TextInput(attrs={'type': 'date'})
        self.fields['date_permiso'].widget = TextInput(attrs={'type': 'date'})
        self.fields['start_time'].widget = TextInput(attrs={'type': 'time'})
        self.fields['end_time'].widget = TextInput(attrs={'type': 'time'})
        self.fields['registered_by'].widget = TextInput(attrs={'readonly': 'readonly'})
        self.fields['employee'].queryset= empleado_actual
        if(empleado_actual):
            self.fields['employee'].initial = empleado_actual[0].pk

apps/permissions/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
import json
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
	CreateView,
	UpdateView,
	DeleteView
)
from apps.permissions.models import TypeOfPermit, Permission
from .forms import TypeOfPermitForm, PermissionForm
from django.http import HttpResponse
from django.views.generic import FormView, TemplateView
from django.contrib.messages.views import SuccessMessageMixin
from apps.accounts.models import UserProfile
# Create your views here.


#Tipos de permiso

def type_of_permit_list(request, template_name='permissions/typeofpermit_list.html'):
    user_profile = UserProfile.objects.get(user=request.user)
    type_of_permit = TypeOfPermit.objects.all()
    data = {}
    data['object_list'] = type_of_permit
    return render(request, template_name, data)


def type_of_permit_create(request, template_name='permissions/typeofpermit_form.html'):
    
    form = TypeOfPermitForm(request.POST or None)  
    if form.is_valid():
        type_of_permit = form.save()
        return redirect('permissions:type_of_permit_list')
    return render(request, template_name, {'form':form})


def type_of_permit_update(request, pk, template_name='permissions/typeofpermit_form.html'):
    type_of_permit = get_object_or_404(TypeOfPermit, pk=pk)
    form = TypeOfPermitForm(request.POST or None, instance=type_of_permit)
    if form.is_valid():
        form.save()
        return redirect('permissions:type_of_permit_list')
    return render(request, template_name, {'form':form})

def type_of_permit_delete(request, pk):
    type_of_permit = get_object_or_404(TypeOfPermit, pk=pk)    
    type_of_permit.delete()
    return redirect('permissions:type_of_permit_list')
    # return render(request, template_name, {'object':type_of_permit})


#Permisos

def permission_list_user(request, template_name='permissions/permission_list.html'):
    user_profile = UserProfile.objects.get(user=request.user)
    permission = Permission.objects.all().order_by('-id')
    data = {}
    data['object_list'] = permission
    return render(request, template_name, data)


def permission_user_create(request,cedula, template_name='permissions/permission_form.html'):
    usuario_actual = request.user.first_name + ' ' + request.user.last_name + ' - ' + request.user.username
    form = PermissionForm(request.POST or None,initial={"registered_by": usuario_actual}, cedula=cedula)
    if form.is_valid():
        permission = form.save()
        return redirect('permissions:permission_list')
    return render(request, template_name, {'form':form, 'create': True})


def permission_user_update(request, pk, template_name='permissions/permission_form.html'):
    permission = get_object_or_404(Permission, pk=pk)
    cedula = permission.employee.person.cedula
    form = PermissionForm(request.POST or None, instance=permission, cedula=cedula)
    if form.is_valid():
        form.save()
        return redirect('permissions:permission_list')
    return render(request, template_name, {'form':form})

def permission_user_delete(request, pk):
    permission = get_object_or_404(Permission, pk=pk)    
    permission.delete()
    return redirect('permissions:permission_list')
    # return render(request, template_name)

apps/permissions/templates/permissions/permission_confirm_delete.html
{% extends "app/base_site.html" %}
{% block content %}
    <form method="post">{% csrf_token %}
        ¿Estás seguro que deseas borrar el permiso "{{ object }}"?
        <input type="submit" value="Eliminar" />
    </form>
{% endblock %}

apps/permissions/templates/permissions/permission_detail.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
      <h1 class="page-header">
        Unidad Institucional
      </h1>
      <ol class="breadcrumb">
        <li>
          <i class="fa fa-dashboard"></i>  <a href="index.html">Inicio</a>
        </li>
        <li class="active">
          <i class="fa fa-edit"></i> <a href="{% url "institution:institution_list_user" %}"> Instituciones</a>
        </li>
        <li class="active">
          <i class="fa fa-edit"></i> <a href="{% url "institution:institutionalunit_list_user" %}"> Unidad Institucional</a>
        </li>
        <li class="active">
          <i class="fa fa-edit"></i> Unidad Institucional Detalle - {{ institutionalunit.institutional_unit }}
        </li>
        
       </ol>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ institutional_unit.institutional_unit }} <a href="{% url "institution:institutionalunit_edit_user" institutional_unit.id %}" class="btn btn-xs btn-default" role="button">Editar</a></h3>
            </div>
            <div class="panel-body">
                <div class="row">
                        <div class="col-lg-6">
                            
                                <div class="panel-body">
                                    <label for="disabledSelect">Unidad Institucional:</label>
                                    <input class="form-control" id="disabledInput" type="text"  disabled="" value="{{ institutional_unit.institutional_unit }}">
                                </div>
                            
                        </div>
                        <div class="col-lg-6">
                            
                              <div class="col-lg-6">
                                <div class="panel-body">
                                        <label for="disabledSelect">Número de Trabajadores:</label>
                                <input class="form-control" id="disabledInput" type="text"  disabled="" value="{{ institutional_unit.number_of_workers }}">
                                </div>
                                
                            </div>
                            <div class="col-lg-6">
                                <div class="panel-body">
                                        <label for="disabledSelect">Número de empleados:</label>
                                <input class="form-control" id="disabledInput" type="text"  disabled="" value="{{ institutional_unit.number_of_employees }}">
                                </div>
                                
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-6">
                            
                                <div class="panel-body">
                                    <label for="disabledSelect">Institución a la que pertenece:</label>
                                    <input class="form-control" id="disabledInput" type="text" placeholder="Disabled input" disabled="" value="{{ institutional_unit.institution }}">
                                </div>
                                            
                        </div>
                         <div class="col-lg-6">
                            
                            	
                            
                        </div>
                        
                    </div>
                     <div class="row">
                        
                        
                    </div>    
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Departamentos</h3>
                </div>
                <div class="panel-body">
                <div class="col-sm-6">
                <div class="table-responsive">
                  <table id="table_instituciones" class="display nowrap dataTable dtr-inline" style="width: 100%;"aria-describedby="example_info">
    <thead>
        <tr>
            <th>Departamento</th>
            <th>Ver</th>
            <th>Editar</th>
            <th>Borrar</th>
        </tr>
    </thead>
    <tbody>
    {% for department in departamentos %}
        <tr>
            <td><li><a href="{% url "institution:department_edit_user" department.id %}">{{ department.department }} </a></li></td>
            <td><a href="{% url "institution:department_detail_user" department.id %}">Ver </a></td>
            <td><a href="{% url "institution:department_edit_user" department.id %}">Editar</a> </td>
            <td><a href="{% url "institution:department_delete_user" department.id %}">Borrar</a> </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
 </div>
                    </div>
                </div>
            </div>         
        </div>
    </div>

    
    <p>
        <a href="{% url "institution:institutionalunit_list_user" %}">   Regresar</a>
    </p>
         




{% endblock %}
{% block javascript %}
   <script>
      var start_date=$('input[name="registration_date"]'); //our date input has the name "date"
      var options={
          format: 'DD/MM/yyyy',
          orientation:"bottom",
          todayHighlight: true,
          autoclose: true,
          language: "es",
      };
      start_date.datepicker(options); //initiali110/26/2015 8:20:59 PM ze plugin
      
    
    </script>

{% endblock %}

apps/permissions/templates/permissions/permission_form.html
{% extends "app/base_site.html" %}
{% load contrato_templatetags %}
{% block content %}
    <div class="right_col" role="main">
        <div class="">
            <div class="title_right"></div>
            <div class="clearfix"></div>
            <div class="x_title">
                <h2>Registro Permisos </h2>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="form-horizontal" method="post">
         {% if create %}
                  <div class="form-group" id="buscadorEmp">
                <label class="col-sm-2 control-label" for="buscador"></label>
                <div class="col-sm-8">
                    <div class="input-group">
                        <input class="form-control" type="number" id="buscador" v-model="cedula"
                               placeholder="Buscar Empleado por cédula"
                               v-on:keyup.enter="buscarEmpleado()">
                        <span class="input-group-btn"><button type="button" class="btn btn-primary"
                                                              v-on:click="buscarEmpleado()">Buscar</button></span>
                    </div>


                </div>
            </div>
            {% endif %}
            <form class="form-horizontal" method="post">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        {{ field.errors }}
                        <label class="col-sm-2 control-label" for="{{ field.name }}">{{ field.label }}</label>
                        <div class="col-sm-8">
                            {{ field|addclass:'form-control' }}
                        </div>

                    </div>
                {% endfor %}
                <div class="ln_solid"></div>
                <div class="form-group">
                    <div class="col-lg-12">
                        <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                            <button type="submit" class="btn btn-success">Guardar</button>
                            <a href="{% url "permissions:permission_list" %}" class="btn btn-primary"
                               role="button">Cancelar</a>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block javascripts %}
    {{ block.super }}

      <script src="/static/js/constans.js"></script>
    <script>
        {#        TODO cambiar URL host en constans.js#}
        {#        var apiURL_usuario = 'http://localhost:8500/accounts/api_user/';#}
        var URL_empleado = HOST+'/permissions/new/';


        var em = new Vue({
            el: '#buscadorEmp',
            delimiters: ['[[', ']]'],
            data: {
                empleado: '',
                cedula: '',
                empleado_id: ''

            },
            methods: {
                buscarEmpleado: function () {
{#                    this.$route.router.go(URL_empleado + this.cedula);#}
                    window.location.replace(URL_empleado + this.cedula)

                }

            }
        });


    </script>
{% endblock javascripts %}

apps/permissions/templates/permissions/permission_list.html
{% extends "app/base_site.html" %}

{% block title %} Municipio de Loja{% endblock title %}

{% block stylesheets %}
    {{ block.super }}
    <link href="/static/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css" rel="stylesheet">
    <link href="/static/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css" rel="stylesheet">

{% endblock stylesheets %}

{% block content %}

    <div class="right_col" role="main">
        <div class="">
            <div class="page-title">
                <div class="title_left">
                    <h3>Permiso
                        <small>Lista de Permiso</small>
                    </h3>
                </div>

                <div class="title_right">
                    <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">

                    </div>
                </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="x_panel">
                        <div class="x_title">
                            <a class="btn btn-success" href="{% url "permissions:permission_new" 0%}">Nuevo Permiso</a>
                            <div class="clearfix"></div>
                        </div>
                        <div class="x_content">

                            <table id="datatable-buttons" class="table table-striped table-bordered">
                                <thead>
                                <tr>
                                    <th>Empleado</th>
                                    <th>Tipo de Permiso</th>
                                    <th>Acción a ejecutar</th>
                                    <th>Fecha de registro</th>
                                    <th>Fecha de permiso</th>
                                    <th>Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for permission in object_list %}
                                    <tr>
                                        <td> {{ permission.employee }}</td>
                                        <td> {{ permission.type_of_permit }}</td>
                                        <td> {{ permission.action }}</td>
                                        <td> {{ permission.registration_date }}</td>
                                        <td>{{ permission.date_permiso }} </td>

                                        <td>
                                            <div class="btn-group" dropdown>
                                                <button type="button" class="btn btn-danger dropdown-toggle"
                                                        data-toggle="dropdown" aria-expanded="false"> <span
                                                        class="fa fa-navicon"></span>
                                                </button>
                                                <ul class="dropdown-menu" role="menu">
                                                    <li><a href="{% url "permissions:permission_edit" permission.id %}">Editar</a>
                                                    </li>
{#                                                    <li>#}
{#                                                        <a href="{% url "permissions:permission_delete" permission.id %}">Borrar</a>#}
{#                                                    </li>#}
                                                     <li><a onClick="eliminar({{ permission.id }})">Borrar</a></li>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



     <!-- Modal -->
    <div class="modal fade" id="modalEliminar" role="dialog">
        <div class="modal-dialog">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Eliminar</h4>
                </div>
                <div class="modal-body">
                <h3>¿Está seguro que desea eliminar el registro?</h3>
                        <div class="modal-footer">
                            <div class="col-md-6">
                                <div class=" btn-group" role="group">
                                   <button type="button" class="btn btn-success" id="confirmar">Aceptar</button>
                                <button type="button" class="btn btn-danger" data-dismiss="modal">Cancelar</button>
                                </div>
                            </div>
                        </div>

                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascripts %}
    {{ block.super }}
    <!-- Datatables -->
    <script src="/static/vendors/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="/static/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>

     <script>

        var id_item;
        function eliminar(id) {
            id_item = id;
            $("#modalEliminar").modal();
        }

        $('#confirmar').click(function () {
            window.location.href = "borrar/" + id_item;
        });


    </script>

{% endblock javascripts %}

apps/permissions/templates/permissions/typeofpermit_confirm_delete.html
{% extends "base.html" %}
{% block content %}    
    <form method="post">{% csrf_token %}
        ¿Estás seguro que deseas borrar el permiso:  "{{ object }}"?
        <input type="submit" value="Eliminar" />
    </form>
{% endblock %}